### ISSUE TITLE
Can you add FightcadeSnes9x to your tool?

### ISSUE THREAD

**Issue by teatocoffee** [Zansword/Fightcade_P2P_Launcher#1]
As described can you add FightcadeSnes9x to your p2p tool?
Thanks.

**Comment by Zansword** [comment]
hi, thanks for your interest.
if i could handle, i will :)

**Comment by Zansword** [comment]
![image](https://github.com/Zansword/Fightcade_P2P_Launcher/assets/55517014/b7aea2be-7d82-4843-bac5-2da7be8b23a6)
